[mysqld]
basedir=D:/MySQL/MySQL Server 8.0
datadir=C:/Users/Lenovo/AppData/Local/Temp/yutu-mysql/data
port=3307
bind-address=127.0.0.1
default_authentication_plugin=mysql_native_password
character-set-server=utf8mb4
collation-server=utf8mb4_general_ci
skip-log-bin
log-error=C:/Users/Lenovo/AppData/Local/Temp/yutu-mysql/mysql-local.err
pid-file=C:/Users/Lenovo/AppData/Local/Temp/yutu-mysql/mysql-local.pid

[client]
port=3307
