spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/yutu_travel?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
